In [223]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import sqrt
%matplotlib inline

In [151]:
df = pd.read_csv("Z:\\Market Access\\EU\\Anand\\python\\code projects\\time_series_multi_variate\\AirQualityUCI\\AirQualityUCI_1.csv", parse_dates=[['Date', 'Time']])
df.dtypes

Date_Time         object
CO(GT)           float64
PT08.S1(CO)      float64
NMHC(GT)         float64
C6H6(GT)         float64
PT08.S2(NMHC)    float64
NOx(GT)          float64
PT08.S3(NOx)     float64
NO2(GT)          float64
PT08.S4(NO2)     float64
PT08.S5(O3)      float64
T                float64
RH               float64
AH               float64
Unnamed: 15      float64
Unnamed: 16      float64
dtype: object

In [152]:
df.tail(60)

,Date_Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
9411,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9412,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9413,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9414,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9415,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9416,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9417,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9418,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9419,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9420,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9421,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9422,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9423,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9424,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9425,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9426,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9427,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9428,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9429,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9430,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9431,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9432,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9433,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9434,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9435,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9436,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9437,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9438,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9439,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9440,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9441,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9442,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9443,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9444,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9445,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9446,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9447,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9448,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9449,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9450,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9451,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9452,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9453,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9454,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9455,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9456,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9457,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9458,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9459,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9460,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9461,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9462,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9463,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9464,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9465,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9466,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9467,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9468,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9469,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9470,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [153]:
df. dtypes

Date_Time         object
CO(GT)           float64
PT08.S1(CO)      float64
NMHC(GT)         float64
C6H6(GT)         float64
PT08.S2(NMHC)    float64
NOx(GT)          float64
PT08.S3(NOx)     float64
NO2(GT)          float64
PT08.S4(NO2)     float64
PT08.S5(O3)      float64
T                float64
RH               float64
AH               float64
Unnamed: 15      float64
Unnamed: 16      float64
dtype: object

In [154]:
type(df)

pandas.core.frame.DataFrame

In [155]:
df['Date_Time'].isna().sum()

0

In [156]:
df['Date_Time'].replace('nan nan', np.nan)

0       3/10/2004 18:00:00
1       3/10/2004 19:00:00
2       3/10/2004 20:00:00
3       3/10/2004 21:00:00
4       3/10/2004 22:00:00
5       3/10/2004 23:00:00
6        3/11/2004 0:00:00
7        3/11/2004 1:00:00
8        3/11/2004 2:00:00
9        3/11/2004 3:00:00
10       3/11/2004 4:00:00
11       3/11/2004 5:00:00
12       3/11/2004 6:00:00
13       3/11/2004 7:00:00
14       3/11/2004 8:00:00
15       3/11/2004 9:00:00
16      3/11/2004 10:00:00
17      3/11/2004 11:00:00
18      3/11/2004 12:00:00
19      3/11/2004 13:00:00
20      3/11/2004 14:00:00
21      3/11/2004 15:00:00
22      3/11/2004 16:00:00
23      3/11/2004 17:00:00
24      3/11/2004 18:00:00
25      3/11/2004 19:00:00
26      3/11/2004 20:00:00
27      3/11/2004 21:00:00
28      3/11/2004 22:00:00
29      3/11/2004 23:00:00
               ...
9441                   NaN
9442                   NaN
9443                   NaN
9444                   NaN
9445                   NaN
9446                   NaN
9447                   NaN
9448                   NaN
9449                   NaN
9450                   NaN
9451                   NaN
9452                   NaN
9453                   NaN
9454                   NaN
9455                   NaN
9456                   NaN
9457                   NaN
9458                   NaN
9459                   NaN
9460                   NaN
9461                   NaN
9462                   NaN
9463                   NaN
9464                   NaN
9465                   NaN
9466                   NaN
9467                   NaN
9468                   NaN
9469                   NaN
9470                   NaN
Name: Date_Time, Length: 9471, dtype: object

In [157]:
df.dropna(how='all', inplace=True)

In [158]:
df['Date_Time'].describe()

count        9471
unique       9358
top       nan nan
freq          114
Name: Date_Time, dtype: object

In [159]:
df['Date_Time'].replace('nan nan', np.nan, inplace=True)

In [160]:
df[df['Date_Time']=='nan nan']['Date_Time']

Series([], Name: Date_Time, dtype: object)

In [188]:
df['Date_Time'] = pd.to_datetime(df['Date_Time'], format='%m/%d/%Y %H:%M:%S')
df.head()

,Date_Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,2004-03-10 18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN
1,2004-03-10 19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN
2,2004-03-10 20:00:00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN
3,2004-03-10 21:00:00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN
4,2004-03-10 22:00:00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN

In [189]:
ndf = df.drop(['Date_Time'], axis=1)
ndf.index=df.Date_Time
ndf.shape[1]

15

In [190]:
nanindex=df.isnull(any(1))

In [187]:
ndf.index

DatetimeIndex(['2004-03-10 18:00:00', '2004-03-10 19:00:00',
               '2004-03-10 20:00:00', '2004-03-10 21:00:00',
               '2004-03-10 22:00:00', '2004-03-10 23:00:00',
               '2004-03-11 00:00:00', '2004-03-11 01:00:00',
               '2004-03-11 02:00:00', '2004-03-11 03:00:00',
               ...
                               'NaT',                 'NaT',
                               'NaT',                 'NaT',
                               'NaT',                 'NaT',
                               'NaT',                 'NaT',
                               'NaT',                 'NaT'],
              dtype='datetime64[ns]', name='Date_Time', length=9471, freq=None)

In [175]:
# The -200 represents missing values. This value is replaced with its value previous day

cols=ndf.columns
for j in cols:
    for i in range(len(ndf)):
        ndf[ndf[j]==-200] = ndf[j][i-1]

In [197]:
# getting dataframe with no NaT in index
ndf=ndf[ndf.index.notnull()]
ndf.columns

Index(['CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)',
       'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)',
       'T', 'RH', 'AH', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [206]:
ndf.drop('Unnamed: 15', axis=1, inplace=True)
ndf.drop('Unnamed: 16', axis=1, inplace=True)

In [214]:
from statsmodels.tsa.vector_ar.vecm import coint_johansen
johan_test_temp = ndf.drop(['CO(GT)'], axis=1)
print(coint_johansen(johan_test_temp, -1,1).eig)

[1.85137431e-01 1.49562379e-01 9.98466990e-02 9.15622257e-02
 6.59920501e-02 5.02055763e-02 4.01484678e-02 3.35580944e-02
 1.84178447e-02 1.50158406e-02 4.14847921e-03 7.21944108e-05]

In [215]:
# Creating train and test sets
train = ndf[:int(0.8*(len(df)))]
test=ndf[int(0.8*len(df)):]

In [216]:
from statsmodels.tsa.vector_ar.var_model import VAR
model = VAR(endog=train)
model_fit=model.fit()

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency H will be used.
  % freq, ValueWarning)

In [218]:
prediction=model_fit.forecast(model_fit.y, steps=len(test))
prediction

array([[ 2.30729387e+00,  1.28155707e+03, -1.94745177e+02, ...,
         6.82931638e+00,  5.12681892e+01, -5.37581779e-01],
       [ 8.13032895e-01,  1.26261393e+03, -1.91100506e+02, ...,
         6.09141856e+00,  4.93181165e+01, -1.55414976e+00],
       [-4.94045742e-01,  1.24272951e+03, -1.88617939e+02, ...,
         5.39106939e+00,  4.76124023e+01, -2.49398205e+00],
       ...,
       [-4.03417068e+01,  1.05250015e+03, -1.50817696e+02, ...,
         1.18589521e+01,  3.98927784e+01, -6.40591767e+00],
       [-4.03417069e+01,  1.05250015e+03, -1.50817696e+02, ...,
         1.18589521e+01,  3.98927784e+01, -6.40591767e+00],
       [-4.03417069e+01,  1.05250015e+03, -1.50817696e+02, ...,
         1.18589521e+01,  3.98927784e+01, -6.40591767e+00]])

In [227]:
pred = pd.DataFrame(index=range(0,len(prediction)),columns=[cols])
for j in range(0,13):
    for i in range(0, len(prediction)):
       pred.iloc[i][j] = prediction[i][j]

    
#check rmse
from sklearn.metrics import mean_squared_error
for i in cols:
    print('rmse value for', i, 'is : ', sqrt(mean_squared_error(pred[i], test[i])))

rmse value for CO(GT) is :  54.058431992152784
rmse value for PT08.S1(CO) is :  342.3750244596943
rmse value for NMHC(GT) is :  50.01515247008202
rmse value for C6H6(GT) is :  45.26899942157515
rmse value for PT08.S2(NMHC) is :  351.79727482885005
rmse value for NOx(GT) is :  250.7790759923259
rmse value for PT08.S3(NOx) is :  323.8453371597583
rmse value for NO2(GT) is :  120.24336293431688
rmse value for PT08.S4(NO2) is :  553.7517256253481
rmse value for PT08.S5(O3) is :  504.1241475719047
rmse value for T is :  46.87494385463556
rmse value for RH is :  56.00157796261648
rmse value for AH is :  43.12205949725111

In [230]:
model=VAR(endog=ndf)
model_fit=model.fit()
yhat=model_fit.forecast(model_fit.y, steps=1)
print(yhat)

[[ 4.83828788e+00  1.07761794e+03 -2.02755723e+02  1.10508004e+01
   1.04519077e+03  2.60751060e+02  6.48193186e+02  1.49439100e+02
   1.15109492e+03  8.46002947e+02  2.60663362e+01  1.44756501e+01
  -6.35797675e-01]]

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency H will be used.
  % freq, ValueWarning)